server:
  port: 8081

spring:
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: